### ISSUE TITLE
Django 1.10 support. 'AppCommand' has no attribute 'option_list'

### ISSUE THREAD

**Issue by KiranPrajapati345** [Brobin/drf-generators#28]
when I run  this command this gives error.
AttributeError: type object 'AppCommand' has no attribute 'option_list'

:(
that's why http://127.0.0.1:8000/ gives me page not found

**Comment by Brobin** [comment]
This is due to your django version. You are using 1.10, correct? They deprecated option_list. I will work on this if I get a chance, but I'm really busy with school at the moment. 

A similar thing is being done, to drop earlier django support on my other repo, if you'd like to give a stab at it yourself. https://github.com/Brobin/django-seed/pull/38/files

**Comment by KiranPrajapati345** [comment]
Thanks for replay.

I have solve that .... And its works,
Just  add fields in api/serializers.py file... Thanks a lot, one of the
best website I never seen ..

**Comment by Zeitvertreib** [comment]
doh, im not getting any clue out of it.. how to solve it?

**Comment by Brobin** [comment]
Install the latest version (0.3.0) and this should be resolved. There were 2 open PRs to fix this, but noone was responding, so I did it myself.
